version: 2.1
setup: true
orbs:
  namespace: namespacelabs/build@0.2.0

jobs:
  testbuild:
    machine:
      image: ubuntu-2204
      resource_class: arm.2xlarge
      docker_layer_caching: false
    steps:
      - checkout
      - namespace/setup
      - run:
          name: docker build
          working_directory: testdata
          command: docker buildx build .

workflows:
  testprod:
    jobs:
      - testbuild
