version: 2.1
setup: true
orbs:
  namespace: namespacelabs/build@0.2.0

jobs:
  build_amd64:
    machine:
      image: ubuntu-2204:2024.08.1
      resource_class: arm.medium
      docker_layer_caching: false
    steps:
      - checkout
      - namespace/setup
      - run:
          name: docker build
          working_directory: testdata
          command: docker buildx build --builder namespace --platform linux/amd64 .

  build_arm64:
    machine:
      image: ubuntu-2204:2024.08.1
      resource_class: arm.medium
      docker_layer_caching: false
    steps:
      - checkout
      - namespace/setup
      - run:
          name: docker build
          working_directory: testdata
          command: docker buildx build --builder namespace --platform linux/arm64 .

workflows:
  testprod:
    jobs:
      - build_amd64
      - build_arm64
